import {
  Archive,
  ArchiveRestore,
  BadgeDollarSign,
  Banknote,
  Boxes,
  Building,
  Building2,
  CalendarCheck,
  CalendarClock,
  CalendarRange,
  Car,
  ClipboardList,
  Coins,
  Contact,
  FileSpreadsheet,
  FolderKanban,
  Fuel,
  Handshake,
  Home,
  Landmark,
  Layers,
  Leaf,
  Map,
  MapPin,
  Mountain,
  Package,
  ReceiptText,
  Repeat,
  ShoppingCart,
  Smartphone,
  Store,
  Target,
  Truck,
  UserCheck,
  UserCog,
  Users,
  Wallet,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const MODULE_ICONS: Record<string, LucideIcon> = {
  departements: Building2,
  fonctions: Layers,
  profils: UserCog,
  employes: Users,
  conges: CalendarRange,
  presences: CalendarCheck,
  salaires: BadgeDollarSign,
  clients: Contact,
  fournisseurs: Truck,
  achats: ShoppingCart,
  ventes: Store,
  budgets: Wallet,
  articles: Package,
  mouvements_stock: Boxes,
  vehicules: Car,
  carburant: Fuel,
  entretiens: Wrench,
  federations: Building,
  unions: Handshake,
  cooperatives: Leaf,
  associations: Users,
  membres: UserCheck,
  intervenants: Contact,
  provinces: Map,
  communes: Home,
  zones: MapPin,
  collines: Mountain,
  "fiches-terrain": ClipboardList,
  imputations: FileSpreadsheet,
  "banque-versements": Banknote,
  "banque-retraits": Coins,
  operations: Repeat,
  transactions_mobile: Smartphone,
  programmes: Target,
  partenaires: Handshake,
  projets: FolderKanban,
  "dossiers-archives": ArchiveRestore,
  archives: Archive,
  planifications: CalendarClock,
};

export const FALLBACK_MODULE_ICON: LucideIcon = ReceiptText;

export const BANK_ICON: LucideIcon = Landmark;
